---
development: &default
  adapter: postgresql
  encoding: unicode
  database: spear
  pool: 5
  username: spear
  password: spear

production:
  <<: *default
  database: spear

test:
  <<: *default
  database: spear_test
